iikocloud:
  api_key: "your_api_key"
  app_id: "your_app_id"
  client_secret: "your_client_secret"
  rate_limits:
    auth:
      max_requests: 1
      time_window_seconds: 5.0
    get_organizations:
      max_requests: 1
      time_window_seconds: 10.0
    get_organization_settings:
      max_requests: 1
      time_window_seconds: 10.0
    create_or_update_customer:
      max_requests: 100
      time_window_seconds: 60.0
    get_customer_info:
      max_requests: 100
      time_window_seconds: 60.0
    delete_customers:
      max_requests: 100
      time_window_seconds: 60.0
    restore_customers:
      max_requests: 100
      time_window_seconds: 60.0
    add_customer_magnet_card:
      max_requests: 100
      time_window_seconds: 60.0
    remove_customer_magnet_card:
      max_requests: 100
      time_window_seconds: 60.0
    add_customer_to_program:
      max_requests: 100
      time_window_seconds: 60.0
    hold_customer_balance:
      max_requests: 100
      time_window_seconds: 60.0
    cancel_customer_balance_hold:
      max_requests: 100
      time_window_seconds: 60.0
    top_up_customer_balance:
      max_requests: 100
      time_window_seconds: 60.0
    withdraw_customer_balance:
      max_requests: 100
      time_window_seconds: 60.0
    get_loyalty_counters:
      max_requests: 10
      time_window_seconds: 60.0
    get_customer_categories:
      max_requests: 1
      time_window_seconds: 60.0
    add_customer_category:
      max_requests: 100
      time_window_seconds: 60.0
    remove_customer_category:
      max_requests: 100
      time_window_seconds: 60.0
    get_terminal_groups:
      max_requests: 10
      time_window_seconds: 60.0
    check_terminal_groups_availability:
      max_requests: 10
      time_window_seconds: 60.0
    get_external_menus:
      max_requests: 1
      time_window_seconds: 1800.0
    get_external_menu_by_id:
      max_requests: 5
      time_window_seconds: 60.0
    get_stop_lists:
      max_requests: 10
      time_window_seconds: 60.0
    add_products_to_stop_list:
      max_requests: 1
      time_window_seconds: 60.0
    remove_products_from_stop_list:
      max_requests: 1
      time_window_seconds: 60.0
    clear_stop_list:
      max_requests: 1
      time_window_seconds: 60.0
    check_products_in_stop_list:
      max_requests: 10
      time_window_seconds: 60.0
    get_nomenclature:
      max_requests: 1
      time_window_seconds: 60.0
    get_combos_info:
      max_requests: 10
      time_window_seconds: 60.0
    calculate_combo_price:
      max_requests: 10
      time_window_seconds: 60.0
    get_cancel_causes:
      max_requests: 1
      time_window_seconds: 60.0
    get_delivery_order_types:
      max_requests: 1
      time_window_seconds: 60.0
    get_payment_types:
      max_requests: 1
      time_window_seconds: 60.0
    get_discounts:
      max_requests: 1
      time_window_seconds: 60.0
    get_removal_types:
      max_requests: 1
      time_window_seconds: 60.0
    get_tips_types:
      max_requests: 1
      time_window_seconds: 60.0
    create_delivery_order:
      max_requests: 20
      time_window_seconds: 60.0
    add_delivery_order_items:
      max_requests: 100
      time_window_seconds: 60.0
    add_delivery_order_payments:
      max_requests: 100
      time_window_seconds: 60.0
    cancel_delivery_order:
      max_requests: 100
      time_window_seconds: 60.0
    cancel_delivery_confirmation:
      max_requests: 100
      time_window_seconds: 60.0
    confirm_delivery:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_comment:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_complete_before:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_driver_info:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_external_data:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_operator:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_payments:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_point:
      max_requests: 100
      time_window_seconds: 60.0
    change_delivery_service_type:
      max_requests: 100
      time_window_seconds: 60.0
    close_delivery_order:
      max_requests: 100
      time_window_seconds: 60.0
    print_delivery_bill:
      max_requests: 100
      time_window_seconds: 60.0
    print_table_order_bill:
      max_requests: 100
      time_window_seconds: 60.0
    update_delivery_order_problem:
      max_requests: 100
      time_window_seconds: 60.0
    update_delivery_order_status:
      max_requests: 100
      time_window_seconds: 60.0
    update_delivery_tracking_link:
      max_requests: 100
      time_window_seconds: 60.0
    get_deliveries_by_delivery_date_and_phone:
      max_requests: 10
      time_window_seconds: 60.0
    get_deliveries_by_delivery_date_and_status:
      max_requests: 10
      time_window_seconds: 60.0
    get_deliveries_by_id:
      max_requests: 10
      time_window_seconds: 60.0
    get_deliveries_by_revision:
      max_requests: 10
      time_window_seconds: 60.0
    get_delivery_history_by_delivery_date_and_phone:
      max_requests: 10
      time_window_seconds: 60.0
    search_deliveries:
      max_requests: 10
      time_window_seconds: 60.0
    get_allowed_delivery_restrictions:
      max_requests: 20
      time_window_seconds: 60.0
    get_delivery_restrictions:
      max_requests: 1
      time_window_seconds: 60.0
    create_delivery_draft:
      max_requests: 100
      time_window_seconds: 60.0
    save_delivery_draft:
      max_requests: 100
      time_window_seconds: 60.0
    commit_delivery_draft:
      max_requests: 20
      time_window_seconds: 60.0
    delete_delivery_draft:
      max_requests: 100
      time_window_seconds: 60.0
    lock_delivery_draft:
      max_requests: 100
      time_window_seconds: 60.0
    unlock_delivery_draft:
      max_requests: 100
      time_window_seconds: 60.0
    get_delivery_draft_by_id:
      max_requests: 20
      time_window_seconds: 60.0
    get_delivery_drafts_by_filter:
      max_requests: 20
      time_window_seconds: 60.0
    get_cities:
      max_requests: 1
      time_window_seconds: 60.0
    get_regions:
      max_requests: 1
      time_window_seconds: 60.0
    get_streets_by_city:
      max_requests: 1
      time_window_seconds: 60.0
    get_streets_by_id:
      max_requests: 1
      time_window_seconds: 60.0
    calculate_loyalty_checkin:
      max_requests: 1000
      time_window_seconds: 60.0
    get_coupon_info:
      max_requests: 10
      time_window_seconds: 60.0
    get_coupon_series:
      max_requests: 1
      time_window_seconds: 60.0
    get_loyalty_manual_conditions:
      max_requests: 1
      time_window_seconds: 60.0
    get_loyalty_programs:
      max_requests: 1
      time_window_seconds: 60.0
    get_non_activated_coupons_by_series:
      max_requests: 10
      time_window_seconds: 60.0
    get_marketing_sources:
      max_requests: 1
      time_window_seconds: 60.0
